version: '3'

services: 
  hello-world: 
    image: node:14-alpine
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports: 
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes: 
      - ./:/app:rw